server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5435/knust_pulse
spring.datasource.username=knust
spring.datasource.password=knust123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.jackson.serialization.write-dates-as-timestamps=false

moderation.service.url=http://localhost:8000
jwt.secret=knust-pulse-dev-secret-key-min-256-bits-long-for-hs256!!
jwt.expiration-ms=86400000
