-- Social features required for the connected MVP.
-- PostgreSQL executes this file automatically on a fresh Docker database.

CREATE TABLE IF NOT EXISTS post_likes (
    id BIGSERIAL PRIMARY KEY,
    post_id INT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_post_like UNIQUE (post_id, user_id)
);

CREATE TABLE IF NOT EXISTS direct_messages (
    id BIGSERIAL PRIMARY KEY,
    sender_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    recipient_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    media_url VARCHAR(500),
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comments_post_created ON comments(post_id, created_at);
CREATE INDEX IF NOT EXISTS idx_post_likes_post ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS idx_direct_messages_pair ON direct_messages(sender_id, recipient_id, created_at);

-- Insert lots of generated users
INSERT INTO users (full_name, email, password_hash, role, college, bio) VALUES
('Platform Admin', 'admin@knust.edu.gh', 'demo123', 'ADMIN_STAFF', 'STAFF_ONLY', 'KNUST Pulse Platform Administrator.'),
('Dr. Grace Asante', 'grace.asante@knust.edu.gh', 'demo123', 'ACADEMIC_STAFF', 'CoE', 'Lecturer, Electrical Engineering. Research focus: sustainable energy.'),
('Kwame Asante-Boateng', 'kwame@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', '3rd year CS. Katanga Hall. Python by day, debug by midnight 💻'),
('Abena Serwaa', 'abena@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Mech Eng Level 400. Almost free. Conti girl 👑'),
('Appiah Agyeman', 'appiah.agyeman0@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Yaa Ofori', 'yaa.ofori1@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Darko Mensah', 'darko.mensah2@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Ofori Ofori', 'ofori.ofori3@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Boateng Agyeman', 'boateng.agyeman4@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Ama Tetteh', 'ama.tetteh5@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Kwesi Nkrumah', 'kwesi.nkrumah6@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Kwabena Asante', 'kwabena.asante7@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Esi Frimpong', 'esi.frimpong8@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Ofori Darko', 'ofori.darko9@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Arthur Appiah', 'arthur.appiah10@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Kwabena Addai', 'kwabena.addai11@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Mensah Arthur', 'mensah.arthur12@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Owusu Boateng', 'owusu.boateng13@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Yaw Asare', 'yaw.asare14@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Asare Arthur', 'asare.arthur15@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Ofori Addai', 'ofori.addai16@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Ofori Ofori', 'ofori.ofori17@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Kofi Sarpong', 'kofi.sarpong18@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Frimpong Ofori', 'frimpong.ofori19@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Nana Aboagye', 'nana.aboagye20@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Afia Asare', 'afia.asare21@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Esi Yeboah', 'esi.yeboah22@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Kwabena Boateng', 'kwabena.boateng23@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Esi Arthur', 'esi.arthur24@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Kofi Owusu', 'kofi.owusu25@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Aboagye Asare', 'aboagye.asare26@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Asante Asante', 'asante.asante27@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Afia Appiah', 'afia.appiah28@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Mensah Nkrumah', 'mensah.nkrumah29@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Yaw Danquah', 'yaw.danquah30@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Owusu Sarpong', 'owusu.sarpong31@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Tetteh Aboagye', 'tetteh.aboagye32@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Yaw Arthur', 'yaw.arthur33@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Kwesi Arthur', 'kwesi.arthur34@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Nana Boakye', 'nana.boakye35@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Kwabena Kusi', 'kwabena.kusi36@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Esi Asante', 'esi.asante37@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Esi Sarpong', 'esi.sarpong38@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Afia Aboagye', 'afia.aboagye39@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Asare Yeboah', 'asare.yeboah40@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Kwesi Nkrumah', 'kwesi.nkrumah41@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Asante Appiah', 'asante.appiah42@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Ofori Asare', 'ofori.asare43@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Appiah Nkrumah', 'appiah.nkrumah44@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Ofori Nkrumah', 'ofori.nkrumah45@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Esi Appiah', 'esi.appiah46@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Ama Darko', 'ama.darko47@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Ofori Ofori', 'ofori.ofori48@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Akosua Addai', 'akosua.addai49@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Amma Asante', 'amma.asante50@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Ofori Arthur', 'ofori.arthur51@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Kwabena Addai', 'kwabena.addai52@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Esi Aboagye', 'esi.aboagye53@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Asante Darko', 'asante.darko54@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Asante Tetteh', 'asante.tetteh55@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Yaw Ofori', 'yaw.ofori56@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Darko Asare', 'darko.asare57@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Kofi Yeboah', 'kofi.yeboah58@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Akosua Sarpong', 'akosua.sarpong59@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Addai Arthur', 'addai.arthur60@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Kwesi Appiah', 'kwesi.appiah61@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Ama Tetteh', 'ama.tetteh62@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Addai Ofori', 'addai.ofori63@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Boateng Boateng', 'boateng.boateng64@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Aboagye Danquah', 'aboagye.danquah65@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Esi Sarpong', 'esi.sarpong66@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Nana Tetteh', 'nana.tetteh67@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Tetteh Asare', 'tetteh.asare68@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Asare Boateng', 'asare.boateng69@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Kweku Asare', 'kweku.asare70@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Kojo Asante', 'kojo.asante71@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Osei Nkrumah', 'osei.nkrumah72@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Esi Aboagye', 'esi.aboagye73@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Afia Yeboah', 'afia.yeboah74@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Abena Addai', 'abena.addai75@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Boateng Mensah', 'boateng.mensah76@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Kwesi Tetteh', 'kwesi.tetteh77@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Aboagye Sarpong', 'aboagye.sarpong78@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Kweku Agyeman', 'kweku.agyeman79@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Yaa Agyeman', 'yaa.agyeman80@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Asare Boateng', 'asare.boateng81@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Kwame Boateng', 'kwame.boateng82@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Kofi Nkrumah', 'kofi.nkrumah83@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Amma Ofori', 'amma.ofori84@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Akosua Danquah', 'akosua.danquah85@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Kwame Appiah', 'kwame.appiah86@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Agyeman Darko', 'agyeman.darko87@st.knust.edu.gh', 'demo123', 'STUDENT', 'CABE', 'Student at CABE'),
('Asante Asante', 'asante.asante88@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Frimpong Asante', 'frimpong.asante89@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Nana Owusu', 'nana.owusu90@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Addai Sarpong', 'addai.sarpong91@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR'),
('Tetteh Asare', 'tetteh.asare92@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Agyeman Darko', 'agyeman.darko93@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoE', 'Student at CoE'),
('Agyeman Ofori', 'agyeman.ofori94@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHSS', 'Student at CoHSS'),
('Asante Boateng', 'asante.boateng95@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Addai Nkrumah', 'addai.nkrumah96@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Kwabena Appiah', 'kwabena.appiah97@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoHS', 'Student at CoHS'),
('Kofi Aboagye', 'kofi.aboagye98@st.knust.edu.gh', 'demo123', 'STUDENT', 'CoS', 'Student at CoS'),
('Kwabena Kusi', 'kwabena.kusi99@st.knust.edu.gh', 'demo123', 'STUDENT', 'CANR', 'Student at CANR')
ON CONFLICT (email) DO NOTHING;

INSERT INTO posts (author_id, community_id, content, post_type, status, views, reposts, shares) VALUES
(28, 2, 'Can''t believe the line for food at Queens Hall today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 341, 14, 11),
(70, 7, 'Just submitted my final project for BIO 204! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 43, 18, 16),
(57, 4, 'Can''t believe the line for food at Brunei today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 442, 13, 7),
(116, 8, 'The wifi in Queens Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 261, 43, 17),
(64, 5, 'Can''t believe the line for food at Queens Hall today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 407, 9, 4),
(81, 3, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 271, 27, 13),
(71, 9, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 373, 28, 21),
(70, 5, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 92, 36, 22),
(25, 2, 'Just submitted my final project for MATH 101! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 249, 28, 1),
(68, 3, 'SRC meeting was interesting today. Hoping to see real changes in Republic Hall.', 'TEXT', 'PUBLISHED', 37, 48, 23),
(53, 3, 'Reminder that the CoS seminar is tomorrow at 2PM.', 'TEXT', 'PUBLISHED', 247, 5, 18),
(66, 3, 'Anyone got past questions for MATH 101?', 'TEXT', 'PUBLISHED', 47, 3, 29),
(104, 4, 'Just submitted my final project for LAW 201! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 475, 4, 22),
(25, 2, 'Looking for a study group for ECON 302, preferably people in CANR.', 'TEXT', 'PUBLISHED', 417, 8, 13),
(98, 3, 'Selling my textbook for ENG 202, DM for price.', 'TEXT', 'PUBLISHED', 59, 6, 13),
(77, 8, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 291, 1, 21),
(36, 5, 'Reminder that the CoHS seminar is tomorrow at 2PM.', 'TEXT', 'PUBLISHED', 96, 5, 23),
(101, 9, 'Lost my student ID near Independence Hall, please DM me if found!', 'TEXT', 'PUBLISHED', 413, 35, 28),
(48, 6, 'Reminder that the CABE seminar is tomorrow at 2PM.', 'TEXT', 'PUBLISHED', 283, 30, 24),
(58, 7, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 373, 20, 4),
(110, 6, 'Anyone got past questions for NURS 105?', 'TEXT', 'PUBLISHED', 47, 12, 9),
(80, 2, 'SRC meeting was interesting today. Hoping to see real changes in Independence Hall.', 'TEXT', 'PUBLISHED', 97, 22, 10),
(112, 1, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 435, 25, 24),
(119, 8, 'Looking for a study group for ECON 302, preferably people in CoE.', 'TEXT', 'PUBLISHED', 356, 42, 30),
(44, 4, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 474, 40, 10),
(64, 9, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 399, 20, 14),
(96, 4, 'Does anyone know if Engineering Block is open late tonight?', 'TEXT', 'PUBLISHED', 476, 2, 28),
(56, 3, 'Just submitted my final project for ARCH 401! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 402, 42, 28),
(78, 6, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 76, 35, 21),
(87, 6, 'Reminder that the CoE seminar is tomorrow at 2PM.', 'TEXT', 'PUBLISHED', 230, 47, 29),
(71, 3, 'Looking for a study group for CHEM 303, preferably people in CoE.', 'TEXT', 'PUBLISHED', 339, 46, 28),
(86, 1, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 392, 21, 18),
(39, 5, 'Reminder that the CABE seminar is tomorrow at 2PM.', 'TEXT', 'PUBLISHED', 77, 4, 28),
(48, 8, 'The wifi in Independence Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 183, 20, 17),
(57, 6, 'Just finished my LAW 201 midsem, that was brutal. Who else is in CoS?', 'TEXT', 'PUBLISHED', 101, 43, 27),
(92, 8, 'Can''t believe the line for food at Katanga today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 46, 33, 7),
(43, 7, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 193, 23, 10),
(101, 6, 'Lost my student ID near Katanga, please DM me if found!', 'TEXT', 'PUBLISHED', 429, 27, 30),
(98, 3, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 310, 32, 6),
(114, 3, 'Looking for a study group for MATH 101, preferably people in CANR.', 'TEXT', 'PUBLISHED', 359, 43, 2),
(69, 5, 'The wifi in Queens Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 312, 25, 24),
(45, 3, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 191, 17, 4),
(51, 7, 'Does anyone know if Engineering Block is open late tonight?', 'TEXT', 'PUBLISHED', 324, 35, 21),
(28, 6, 'Just submitted my final project for NURS 105! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 496, 24, 30),
(98, 4, 'The wifi in Independence Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 224, 50, 19),
(54, 7, 'Just finished my CHEM 303 midsem, that was brutal. Who else is in CoHSS?', 'TEXT', 'PUBLISHED', 199, 27, 9),
(78, 4, 'The wifi in Independence Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 325, 24, 2),
(29, 4, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 404, 12, 14),
(67, 7, 'Looking for a study group for LAW 201, preferably people in CABE.', 'TEXT', 'PUBLISHED', 362, 22, 26),
(32, 4, 'Looking for a study group for CHEM 303, preferably people in CoHS.', 'TEXT', 'PUBLISHED', 460, 21, 2),
(58, 3, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 339, 3, 21),
(112, 2, 'Can''t believe the line for food at Engineering Block today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 192, 38, 11),
(61, 3, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 231, 26, 8),
(108, 4, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 361, 3, 5),
(36, 9, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 142, 39, 16),
(84, 2, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 53, 13, 1),
(116, 4, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 455, 35, 18),
(61, 9, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 174, 47, 30),
(75, 6, 'Does anyone know if Brunei is open late tonight?', 'TEXT', 'PUBLISHED', 319, 6, 23),
(87, 2, 'Looking for a study group for BIO 204, preferably people in CANR.', 'TEXT', 'PUBLISHED', 495, 47, 19),
(38, 1, 'Lost my student ID near Queens Hall, please DM me if found!', 'TEXT', 'PUBLISHED', 81, 32, 22),
(86, 2, 'Selling my textbook for BIO 204, DM for price.', 'TEXT', 'PUBLISHED', 421, 9, 0),
(49, 5, 'Just finished my NURS 105 midsem, that was brutal. Who else is in CANR?', 'TEXT', 'PUBLISHED', 95, 3, 22),
(64, 8, 'Looking for a study group for NURS 105, preferably people in CoE.', 'TEXT', 'PUBLISHED', 173, 20, 5),
(74, 9, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 202, 19, 17),
(69, 6, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 472, 44, 9),
(100, 3, 'Anyone got past questions for ARCH 401?', 'TEXT', 'PUBLISHED', 220, 36, 23),
(117, 6, 'Looking for a study group for MATH 101, preferably people in CoHS.', 'TEXT', 'PUBLISHED', 114, 35, 27),
(63, 8, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 208, 13, 14),
(59, 9, 'SRC meeting was interesting today. Hoping to see real changes in Prempeh II Library.', 'TEXT', 'PUBLISHED', 84, 12, 13),
(38, 6, 'Can''t believe the line for food at Republic Hall today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 326, 13, 12),
(75, 8, 'Just finished my ECON 302 midsem, that was brutal. Who else is in CANR?', 'TEXT', 'PUBLISHED', 186, 48, 23),
(53, 8, 'Lost my student ID near Katanga, please DM me if found!', 'TEXT', 'PUBLISHED', 309, 17, 16),
(67, 2, 'Anyone got past questions for MATH 101?', 'TEXT', 'PUBLISHED', 285, 18, 24),
(69, 1, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 470, 14, 11),
(74, 4, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 46, 27, 24),
(32, 4, 'Anyone got past questions for ARCH 401?', 'TEXT', 'PUBLISHED', 286, 1, 17),
(101, 7, 'Lost my student ID near Independence Hall, please DM me if found!', 'TEXT', 'PUBLISHED', 286, 14, 24),
(34, 8, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 192, 6, 25),
(57, 8, 'Looking for a study group for MATH 101, preferably people in CANR.', 'TEXT', 'PUBLISHED', 251, 33, 4),
(37, 9, 'Just finished my ARCH 401 midsem, that was brutal. Who else is in CABE?', 'TEXT', 'PUBLISHED', 230, 19, 1),
(28, 9, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 418, 34, 11),
(67, 4, 'Can''t believe the line for food at Commercial Area today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 490, 22, 21),
(46, 9, 'Just submitted my final project for ECON 302! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 323, 29, 1),
(110, 9, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 175, 47, 18),
(120, 2, 'Lost my student ID near Republic Hall, please DM me if found!', 'TEXT', 'PUBLISHED', 138, 25, 1),
(78, 3, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 75, 47, 15),
(93, 9, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 335, 46, 20),
(86, 2, 'Can''t believe the line for food at Commercial Area today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 463, 11, 30),
(115, 4, 'Just finished my LAW 201 midsem, that was brutal. Who else is in CoS?', 'TEXT', 'PUBLISHED', 80, 42, 18),
(122, 3, 'Just finished my MATH 101 midsem, that was brutal. Who else is in CoE?', 'TEXT', 'PUBLISHED', 361, 21, 28),
(96, 2, 'Anyone got past questions for MATH 101?', 'TEXT', 'PUBLISHED', 24, 22, 18),
(85, 4, 'Does anyone know if Independence Hall is open late tonight?', 'TEXT', 'PUBLISHED', 296, 32, 24),
(57, 7, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 380, 14, 8),
(102, 9, 'Does anyone know if Engineering Block is open late tonight?', 'TEXT', 'PUBLISHED', 241, 14, 22),
(33, 3, 'Anyone got past questions for ARCH 401?', 'TEXT', 'PUBLISHED', 379, 0, 2),
(81, 8, 'Anyone got past questions for CHEM 303?', 'TEXT', 'PUBLISHED', 11, 50, 28),
(49, 5, 'Selling my textbook for ENG 202, DM for price.', 'TEXT', 'PUBLISHED', 174, 30, 19),
(59, 4, 'Can''t believe the line for food at Queens Hall today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 352, 14, 26),
(28, 2, 'Looking for a study group for CS 301, preferably people in CoHSS.', 'TEXT', 'PUBLISHED', 476, 0, 29),
(57, 1, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 208, 19, 6),
(105, 2, 'Reminder that the CANR seminar is tomorrow at 2PM.', 'TEXT', 'PUBLISHED', 336, 48, 22),
(114, 6, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 62, 34, 5),
(87, 6, 'Lost my student ID near Republic Hall, please DM me if found!', 'TEXT', 'PUBLISHED', 278, 16, 28),
(101, 4, 'SRC meeting was interesting today. Hoping to see real changes in Commercial Area.', 'TEXT', 'PUBLISHED', 66, 3, 23),
(51, 8, 'SRC meeting was interesting today. Hoping to see real changes in Republic Hall.', 'TEXT', 'PUBLISHED', 180, 49, 22),
(60, 1, 'Anyone got past questions for ENG 202?', 'TEXT', 'PUBLISHED', 496, 47, 5),
(25, 4, 'Selling my textbook for ARCH 401, DM for price.', 'TEXT', 'PUBLISHED', 57, 37, 12),
(77, 7, 'SRC meeting was interesting today. Hoping to see real changes in Prempeh II Library.', 'TEXT', 'PUBLISHED', 253, 5, 8),
(29, 8, 'Can''t believe the line for food at Engineering Block today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 328, 20, 16),
(47, 9, 'Selling my textbook for CHEM 303, DM for price.', 'TEXT', 'PUBLISHED', 195, 17, 15),
(31, 8, 'SRC meeting was interesting today. Hoping to see real changes in Commercial Area.', 'TEXT', 'PUBLISHED', 313, 27, 0),
(116, 8, 'Just submitted my final project for CHEM 303! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 492, 30, 4),
(74, 4, 'Anyone got past questions for ENG 202?', 'TEXT', 'PUBLISHED', 353, 38, 8),
(110, 4, 'SRC meeting was interesting today. Hoping to see real changes in Prempeh II Library.', 'TEXT', 'PUBLISHED', 202, 47, 24),
(32, 4, 'Does anyone know if Engineering Block is open late tonight?', 'TEXT', 'PUBLISHED', 377, 12, 21),
(77, 5, 'The wifi in Brunei is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 296, 40, 3),
(123, 4, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 186, 14, 25),
(54, 8, 'Lost my student ID near Prempeh II Library, please DM me if found!', 'TEXT', 'PUBLISHED', 251, 17, 12),
(29, 6, 'Does anyone know if Commercial Area is open late tonight?', 'TEXT', 'PUBLISHED', 448, 3, 29),
(110, 4, 'Lost my student ID near Brunei, please DM me if found!', 'TEXT', 'PUBLISHED', 322, 49, 9),
(34, 3, 'Just finished my LAW 201 midsem, that was brutal. Who else is in CANR?', 'TEXT', 'PUBLISHED', 170, 25, 26),
(106, 6, 'Can''t believe the line for food at Republic Hall today. Totally not worth the wait.', 'TEXT', 'PUBLISHED', 434, 6, 6),
(97, 1, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 244, 45, 11),
(100, 1, 'The wifi in Republic Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 166, 43, 10),
(96, 4, 'The wifi in Commercial Area is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 124, 45, 5),
(50, 8, 'Good morning KNUST! Beautiful day on campus.', 'TEXT', 'PUBLISHED', 30, 37, 16),
(107, 2, 'The wifi in Republic Hall is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 263, 14, 13),
(72, 8, 'Lost my student ID near Prempeh II Library, please DM me if found!', 'TEXT', 'PUBLISHED', 366, 36, 12),
(111, 5, 'Just submitted my final project for ARCH 401! Time to sleep for 3 days.', 'TEXT', 'PUBLISHED', 34, 30, 3),
(24, 9, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 473, 27, 9),
(91, 8, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 15, 0, 13),
(83, 6, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 268, 47, 30),
(88, 5, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 47, 21, 14),
(103, 5, 'Anyone got past questions for BIO 204?', 'TEXT', 'PUBLISHED', 134, 33, 4),
(47, 8, 'The wifi in Prempeh II Library is actually decent today. A miracle!', 'TEXT', 'PUBLISHED', 230, 18, 19),
(122, 3, 'Selling my textbook for CS 301, DM for price.', 'TEXT', 'PUBLISHED', 130, 49, 1),
(57, 9, 'Meme of the day: when the lecturer says ''this won''t be on the exam'' and it''s question 1.', 'TEXT', 'PUBLISHED', 287, 7, 21),
(121, 8, 'Anyone got past questions for BIO 204?', 'TEXT', 'PUBLISHED', 403, 30, 14),
(114, 9, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 264, 2, 13),
(96, 1, 'Looking for a study group for ENG 202, preferably people in CoS.', 'TEXT', 'PUBLISHED', 58, 23, 9),
(63, 3, 'SRC meeting was interesting today. Hoping to see real changes in Independence Hall.', 'TEXT', 'PUBLISHED', 294, 2, 24),
(110, 6, 'Anyone got past questions for LAW 201?', 'TEXT', 'PUBLISHED', 170, 7, 4),
(46, 3, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 263, 38, 25),
(50, 1, 'Anyone got past questions for ENG 202?', 'TEXT', 'PUBLISHED', 104, 41, 10),
(37, 8, 'Just finished my CHEM 303 midsem, that was brutal. Who else is in CANR?', 'TEXT', 'PUBLISHED', 230, 39, 30),
(102, 5, 'Looking for a study group for ECON 302, preferably people in CoHS.', 'TEXT', 'PUBLISHED', 223, 39, 12),
(56, 6, 'Selling my textbook for LAW 201, DM for price.', 'TEXT', 'PUBLISHED', 166, 43, 25),
(75, 4, 'Anyone want to play FIFA in the hall later?', 'TEXT', 'PUBLISHED', 311, 39, 21),
(32, 8, 'The new SRC initiative is finally taking off, glad to see it.', 'TEXT', 'PUBLISHED', 294, 39, 6);

INSERT INTO followers (follower_id, following_id) VALUES
(59, 57),
(99, 119),
(87, 90),
(110, 34),
(71, 63),
(89, 28),
(36, 115),
(26, 66),
(63, 67),
(79, 28),
(117, 33),
(84, 29),
(91, 74),
(106, 87),
(47, 86),
(88, 100),
(53, 58),
(36, 41),
(66, 47),
(76, 118),
(73, 98),
(56, 53),
(77, 82),
(105, 47),
(110, 58),
(52, 38),
(47, 77),
(111, 106),
(104, 119),
(42, 30),
(114, 68),
(103, 54),
(25, 64),
(87, 29),
(86, 44),
(45, 69),
(67, 100),
(82, 88),
(57, 71),
(78, 33),
(69, 120),
(79, 87),
(83, 32),
(116, 40),
(37, 82),
(94, 78),
(55, 71),
(72, 104),
(29, 55),
(78, 51),
(61, 103),
(55, 94),
(27, 107),
(54, 95),
(69, 102),
(86, 117),
(42, 50),
(113, 27),
(90, 116),
(83, 62),
(50, 37),
(53, 24),
(53, 99),
(122, 55),
(75, 53),
(79, 97),
(26, 76),
(25, 98),
(111, 84),
(96, 51),
(99, 96),
(59, 90),
(109, 52),
(30, 25),
(26, 104),
(63, 106),
(93, 86),
(41, 96),
(97, 48),
(101, 114),
(90, 108),
(45, 36),
(61, 38),
(81, 61),
(104, 62),
(92, 63),
(108, 73),
(28, 120),
(111, 102),
(38, 117),
(101, 99),
(117, 110),
(94, 65),
(32, 105),
(31, 70),
(65, 66),
(50, 115),
(33, 47),
(118, 46),
(76, 61),
(106, 79),
(48, 58),
(89, 113),
(38, 25),
(78, 104),
(103, 67),
(80, 54),
(86, 75),
(56, 80),
(37, 108),
(80, 105),
(115, 43),
(106, 46),
(31, 99),
(119, 41),
(122, 75),
(87, 77),
(115, 101),
(55, 48),
(70, 52),
(44, 93),
(55, 32),
(87, 76),
(37, 107),
(105, 113),
(60, 90),
(61, 78),
(113, 47),
(69, 50),
(91, 52),
(97, 112),
(60, 65),
(106, 62),
(80, 122),
(118, 101),
(65, 119),
(39, 34),
(105, 92),
(119, 69),
(117, 113),
(95, 51),
(29, 62),
(51, 75),
(59, 122),
(74, 76),
(87, 119),
(108, 95),
(121, 57),
(93, 44),
(119, 31),
(32, 51),
(30, 122),
(91, 54),
(103, 87),
(26, 27),
(111, 62),
(89, 64),
(48, 78),
(122, 36),
(76, 90),
(91, 97),
(91, 57),
(122, 108),
(32, 42),
(85, 100),
(88, 121),
(60, 112),
(32, 44),
(123, 34),
(40, 41),
(91, 35),
(37, 96),
(110, 78),
(26, 37),
(88, 28),
(59, 82),
(87, 94),
(80, 95),
(82, 67),
(110, 50),
(120, 54),
(95, 101),
(104, 99),
(118, 56),
(40, 102),
(77, 89),
(92, 43),
(82, 64),
(113, 57),
(66, 101),
(24, 93),
(38, 108),
(40, 101),
(42, 81),
(66, 114),
(94, 122),
(112, 36),
(89, 66),
(39, 52),
(35, 34),
(78, 50),
(91, 81),
(101, 55),
(93, 75),
(72, 78),
(97, 94),
(49, 115),
(29, 63),
(82, 38),
(115, 73),
(71, 76),
(94, 40),
(113, 37),
(115, 69),
(102, 116),
(65, 60),
(36, 78),
(97, 85),
(30, 41),
(68, 26),
(25, 88),
(96, 92),
(77, 24),
(122, 111),
(31, 93),
(43, 84),
(31, 107),
(115, 102),
(65, 38),
(34, 50),
(41, 86),
(90, 74),
(66, 56),
(100, 49),
(41, 108),
(123, 72),
(49, 97),
(115, 39),
(117, 89),
(86, 83),
(28, 41),
(90, 31),
(96, 98),
(25, 43),
(29, 84),
(96, 62),
(28, 107),
(122, 85),
(30, 97),
(114, 67),
(30, 90),
(89, 77),
(44, 24),
(79, 53),
(50, 87),
(42, 82),
(119, 93),
(110, 59),
(57, 109),
(24, 80),
(24, 52),
(109, 60),
(118, 83),
(64, 113),
(70, 65),
(90, 32),
(65, 110),
(81, 40),
(97, 47),
(50, 36),
(86, 77),
(28, 119),
(46, 81),
(116, 88),
(98, 53),
(86, 66),
(66, 93),
(119, 33),
(69, 25),
(50, 119),
(39, 59),
(102, 106),
(30, 108),
(36, 77),
(27, 97),
(69, 70),
(115, 50),
(108, 82),
(90, 42),
(35, 60),
(91, 108),
(66, 78),
(58, 110),
(92, 39);


-- Generate Comments
INSERT INTO comments (post_id, author_id, content, created_at) VALUES
(127, 6, 'Don''t remind me 😭😭', CURRENT_TIMESTAMP - interval '24 hours'),
(19, 32, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '29 hours'),
(132, 23, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '23 hours'),
(142, 21, 'Lmaooo', CURRENT_TIMESTAMP - interval '24 hours'),
(73, 26, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '40 hours'),
(112, 75, 'God bless you for this', CURRENT_TIMESTAMP - interval '37 hours'),
(121, 44, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '15 hours'),
(140, 2, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '13 hours'),
(120, 31, 'Same here 😭', CURRENT_TIMESTAMP - interval '10 hours'),
(70, 56, 'Help me please 😭', CURRENT_TIMESTAMP - interval '39 hours'),
(5, 66, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '1 hours'),
(9, 31, 'Real', CURRENT_TIMESTAMP - interval '5 hours'),
(106, 9, 'Help me please 😭', CURRENT_TIMESTAMP - interval '34 hours'),
(116, 76, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '23 hours'),
(38, 7, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '41 hours'),
(83, 32, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '24 hours'),
(63, 65, 'Nah this is wild', CURRENT_TIMESTAMP - interval '37 hours'),
(29, 2, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '33 hours'),
(19, 72, 'I''m actually struggling with this topic', CURRENT_TIMESTAMP - interval '34 hours'),
(97, 53, 'Fr 😭', CURRENT_TIMESTAMP - interval '22 hours'),
(29, 22, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '19 hours'),
(50, 20, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '28 hours'),
(4, 7, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '26 hours'),
(135, 97, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '48 hours'),
(121, 69, 'Fr 😭', CURRENT_TIMESTAMP - interval '29 hours'),
(94, 22, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '38 hours'),
(36, 46, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '15 hours'),
(24, 44, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '16 hours'),
(117, 72, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '2 hours'),
(89, 83, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '9 hours'),
(121, 80, 'Don''t remind me 😭😭', CURRENT_TIMESTAMP - interval '2 hours'),
(144, 98, 'This is so true', CURRENT_TIMESTAMP - interval '48 hours'),
(80, 31, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '18 hours'),
(72, 45, 'This is so true', CURRENT_TIMESTAMP - interval '36 hours'),
(99, 60, 'Facts 💯', CURRENT_TIMESTAMP - interval '32 hours'),
(70, 79, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '33 hours'),
(52, 40, 'Real', CURRENT_TIMESTAMP - interval '1 hours'),
(120, 23, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '13 hours'),
(1, 93, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '3 hours'),
(109, 51, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '38 hours'),
(27, 43, 'Check your DMs', CURRENT_TIMESTAMP - interval '20 hours'),
(87, 12, 'Real', CURRENT_TIMESTAMP - interval '1 hours'),
(117, 75, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '30 hours'),
(50, 78, 'Facts 💯', CURRENT_TIMESTAMP - interval '12 hours'),
(85, 95, 'Same here 😭', CURRENT_TIMESTAMP - interval '36 hours'),
(2, 93, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '45 hours'),
(41, 80, 'Wait, since when?', CURRENT_TIMESTAMP - interval '30 hours'),
(55, 7, 'God bless you for this', CURRENT_TIMESTAMP - interval '6 hours'),
(102, 64, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '40 hours'),
(53, 54, 'Don''t remind me 😭😭', CURRENT_TIMESTAMP - interval '45 hours'),
(75, 30, 'Nah this is wild', CURRENT_TIMESTAMP - interval '3 hours'),
(103, 46, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '17 hours'),
(87, 49, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '38 hours'),
(96, 48, 'God bless you for this', CURRENT_TIMESTAMP - interval '38 hours'),
(132, 38, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '8 hours'),
(102, 67, 'Facts 💯', CURRENT_TIMESTAMP - interval '44 hours'),
(28, 81, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '35 hours'),
(40, 81, 'Lmaooo', CURRENT_TIMESTAMP - interval '28 hours'),
(33, 20, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '3 hours'),
(106, 64, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '42 hours'),
(59, 46, 'Don''t remind me 😭😭', CURRENT_TIMESTAMP - interval '20 hours'),
(34, 78, 'Lmaooo', CURRENT_TIMESTAMP - interval '5 hours'),
(11, 44, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '48 hours'),
(66, 26, 'Mood', CURRENT_TIMESTAMP - interval '36 hours'),
(82, 50, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '9 hours'),
(71, 4, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '35 hours'),
(37, 75, 'Help me please 😭', CURRENT_TIMESTAMP - interval '38 hours'),
(128, 19, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '34 hours'),
(4, 12, 'I''m actually struggling with this topic', CURRENT_TIMESTAMP - interval '45 hours'),
(42, 10, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '17 hours'),
(108, 87, 'I''m actually struggling with this topic', CURRENT_TIMESTAMP - interval '12 hours'),
(133, 99, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '33 hours'),
(110, 2, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '42 hours'),
(142, 79, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '28 hours'),
(81, 62, 'Real', CURRENT_TIMESTAMP - interval '15 hours'),
(149, 90, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '17 hours'),
(55, 97, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '28 hours'),
(101, 1, 'I need a study group for this', CURRENT_TIMESTAMP - interval '40 hours'),
(66, 44, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '38 hours'),
(26, 26, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '39 hours'),
(23, 79, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '5 hours'),
(109, 21, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '43 hours'),
(52, 62, 'Can someone explain this?', CURRENT_TIMESTAMP - interval '44 hours'),
(88, 85, 'God bless you for this', CURRENT_TIMESTAMP - interval '36 hours'),
(55, 43, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '48 hours'),
(96, 88, 'Facts 💯', CURRENT_TIMESTAMP - interval '37 hours'),
(132, 5, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '36 hours'),
(121, 42, 'Same here 😭', CURRENT_TIMESTAMP - interval '16 hours'),
(99, 88, 'Real', CURRENT_TIMESTAMP - interval '20 hours'),
(63, 99, 'Real', CURRENT_TIMESTAMP - interval '3 hours'),
(79, 41, 'Lmaooo', CURRENT_TIMESTAMP - interval '29 hours'),
(55, 76, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '7 hours'),
(31, 29, 'Nah this is wild', CURRENT_TIMESTAMP - interval '29 hours'),
(134, 48, 'Wait, since when?', CURRENT_TIMESTAMP - interval '33 hours'),
(109, 55, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '19 hours'),
(67, 88, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '5 hours'),
(4, 60, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '6 hours'),
(10, 86, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '14 hours'),
(126, 7, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '41 hours'),
(136, 34, 'Lmaooo', CURRENT_TIMESTAMP - interval '10 hours'),
(31, 73, 'The accuracy is scary', CURRENT_TIMESTAMP - interval '5 hours'),
(104, 41, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '13 hours'),
(98, 7, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '9 hours'),
(150, 95, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '10 hours'),
(18, 34, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '44 hours'),
(34, 61, 'This is so true', CURRENT_TIMESTAMP - interval '13 hours'),
(104, 56, 'I need a study group for this', CURRENT_TIMESTAMP - interval '27 hours'),
(77, 90, 'Nah this is wild', CURRENT_TIMESTAMP - interval '27 hours'),
(83, 97, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '33 hours'),
(10, 41, 'Mood', CURRENT_TIMESTAMP - interval '1 hours'),
(82, 94, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '18 hours'),
(98, 97, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '18 hours'),
(70, 40, 'Nah this is wild', CURRENT_TIMESTAMP - interval '11 hours'),
(140, 71, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '21 hours'),
(140, 39, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '33 hours'),
(110, 37, 'Can someone explain this?', CURRENT_TIMESTAMP - interval '36 hours'),
(37, 79, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '15 hours'),
(147, 10, 'Facts 💯', CURRENT_TIMESTAMP - interval '18 hours'),
(68, 47, 'Real', CURRENT_TIMESTAMP - interval '13 hours'),
(7, 86, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '31 hours'),
(82, 8, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '38 hours'),
(63, 61, 'Real', CURRENT_TIMESTAMP - interval '24 hours'),
(51, 63, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '47 hours'),
(20, 3, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '43 hours'),
(102, 35, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '42 hours'),
(11, 32, 'Can someone explain this?', CURRENT_TIMESTAMP - interval '31 hours'),
(52, 18, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '16 hours'),
(19, 44, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '33 hours'),
(50, 10, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '41 hours'),
(138, 14, 'Thanks for sharing!', CURRENT_TIMESTAMP - interval '21 hours'),
(50, 37, 'Facts 💯', CURRENT_TIMESTAMP - interval '26 hours'),
(26, 70, 'This is so true', CURRENT_TIMESTAMP - interval '12 hours'),
(68, 19, 'This is so true', CURRENT_TIMESTAMP - interval '41 hours'),
(129, 10, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '25 hours'),
(65, 45, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '45 hours'),
(98, 65, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '8 hours'),
(61, 1, 'Can someone explain this?', CURRENT_TIMESTAMP - interval '17 hours'),
(48, 13, 'Thanks for sharing!', CURRENT_TIMESTAMP - interval '30 hours'),
(78, 57, 'Same here 😭', CURRENT_TIMESTAMP - interval '17 hours'),
(139, 60, 'Real', CURRENT_TIMESTAMP - interval '44 hours'),
(114, 40, 'Check your DMs', CURRENT_TIMESTAMP - interval '2 hours'),
(68, 19, 'Real', CURRENT_TIMESTAMP - interval '5 hours'),
(108, 81, 'Help me please 😭', CURRENT_TIMESTAMP - interval '15 hours'),
(46, 28, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '3 hours'),
(62, 14, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '33 hours'),
(62, 95, 'Facts 💯', CURRENT_TIMESTAMP - interval '33 hours'),
(149, 14, 'Wait, since when?', CURRENT_TIMESTAMP - interval '10 hours'),
(148, 44, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '23 hours'),
(19, 64, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '42 hours'),
(131, 82, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '18 hours'),
(92, 47, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '35 hours'),
(91, 50, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '16 hours'),
(39, 88, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '44 hours'),
(27, 9, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '37 hours'),
(149, 10, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '33 hours'),
(73, 79, 'The accuracy is scary', CURRENT_TIMESTAMP - interval '16 hours'),
(107, 97, 'God bless you for this', CURRENT_TIMESTAMP - interval '27 hours'),
(109, 66, 'The accuracy is scary', CURRENT_TIMESTAMP - interval '25 hours'),
(28, 55, 'Facts 💯', CURRENT_TIMESTAMP - interval '37 hours'),
(128, 90, 'The accuracy is scary', CURRENT_TIMESTAMP - interval '36 hours'),
(63, 89, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '5 hours'),
(30, 36, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '40 hours'),
(71, 5, 'The accuracy is scary', CURRENT_TIMESTAMP - interval '12 hours'),
(73, 94, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '8 hours'),
(97, 87, 'Thanks for sharing!', CURRENT_TIMESTAMP - interval '9 hours'),
(49, 88, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '39 hours'),
(145, 39, 'Fr 😭', CURRENT_TIMESTAMP - interval '30 hours'),
(88, 31, 'Facts 💯', CURRENT_TIMESTAMP - interval '44 hours'),
(33, 75, 'Don''t remind me 😭😭', CURRENT_TIMESTAMP - interval '32 hours'),
(61, 50, 'Can someone explain this?', CURRENT_TIMESTAMP - interval '46 hours'),
(71, 27, 'Thanks for sharing!', CURRENT_TIMESTAMP - interval '12 hours'),
(126, 48, 'I need a study group for this', CURRENT_TIMESTAMP - interval '13 hours'),
(77, 29, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '29 hours'),
(101, 28, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '19 hours'),
(148, 33, 'Bro I can''t even', CURRENT_TIMESTAMP - interval '27 hours'),
(24, 67, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '9 hours'),
(115, 37, 'Don''t remind me 😭😭', CURRENT_TIMESTAMP - interval '9 hours'),
(51, 25, 'Check your DMs', CURRENT_TIMESTAMP - interval '10 hours'),
(149, 29, 'Same here 😭', CURRENT_TIMESTAMP - interval '25 hours'),
(59, 1, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '37 hours'),
(95, 58, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '24 hours'),
(71, 22, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '18 hours'),
(106, 60, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '10 hours'),
(72, 76, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '29 hours'),
(95, 43, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '28 hours'),
(70, 12, 'Facts 💯', CURRENT_TIMESTAMP - interval '20 hours'),
(78, 49, 'Fr 😭', CURRENT_TIMESTAMP - interval '9 hours'),
(103, 96, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '19 hours'),
(149, 14, 'Facts 💯', CURRENT_TIMESTAMP - interval '13 hours'),
(79, 7, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '31 hours'),
(59, 11, 'Lmaooo', CURRENT_TIMESTAMP - interval '1 hours'),
(13, 71, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '6 hours'),
(112, 16, 'God bless you for this', CURRENT_TIMESTAMP - interval '17 hours'),
(102, 93, 'Check your DMs', CURRENT_TIMESTAMP - interval '1 hours'),
(143, 30, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '16 hours'),
(137, 37, 'God bless you for this', CURRENT_TIMESTAMP - interval '20 hours'),
(14, 73, 'Thanks for sharing!', CURRENT_TIMESTAMP - interval '25 hours'),
(13, 66, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '20 hours'),
(3, 91, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '5 hours'),
(19, 100, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '21 hours'),
(100, 62, 'Same here 😭', CURRENT_TIMESTAMP - interval '27 hours'),
(66, 55, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '32 hours'),
(147, 83, 'Check your DMs', CURRENT_TIMESTAMP - interval '7 hours'),
(80, 38, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '38 hours'),
(125, 58, 'I''m dead 💀', CURRENT_TIMESTAMP - interval '36 hours'),
(131, 40, 'Real', CURRENT_TIMESTAMP - interval '12 hours'),
(7, 61, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '2 hours'),
(75, 4, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '30 hours'),
(32, 86, 'Katanga all the way 🔥', CURRENT_TIMESTAMP - interval '25 hours'),
(135, 40, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '47 hours'),
(61, 57, 'I need a study group for this', CURRENT_TIMESTAMP - interval '3 hours'),
(104, 57, 'Check your DMs', CURRENT_TIMESTAMP - interval '39 hours'),
(47, 94, 'I need a study group for this', CURRENT_TIMESTAMP - interval '41 hours'),
(137, 36, 'God bless you for this', CURRENT_TIMESTAMP - interval '31 hours'),
(26, 55, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '26 hours'),
(40, 43, 'I need a study group for this', CURRENT_TIMESTAMP - interval '28 hours'),
(142, 75, 'Lmaooo', CURRENT_TIMESTAMP - interval '38 hours'),
(109, 53, 'I''m actually struggling with this topic', CURRENT_TIMESTAMP - interval '35 hours'),
(44, 48, 'Wait, since when?', CURRENT_TIMESTAMP - interval '15 hours'),
(93, 95, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '9 hours'),
(97, 55, 'Facts 💯', CURRENT_TIMESTAMP - interval '28 hours'),
(70, 98, 'Same here 😭', CURRENT_TIMESTAMP - interval '30 hours'),
(29, 96, 'Same here 😭', CURRENT_TIMESTAMP - interval '12 hours'),
(8, 54, 'Fr 😭', CURRENT_TIMESTAMP - interval '34 hours'),
(54, 92, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '8 hours'),
(104, 62, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '1 hours'),
(71, 40, 'Which lecturer is this? 😂', CURRENT_TIMESTAMP - interval '12 hours'),
(133, 79, 'Mood', CURRENT_TIMESTAMP - interval '14 hours'),
(138, 74, 'Who else is studying right now?', CURRENT_TIMESTAMP - interval '39 hours'),
(48, 73, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '3 hours'),
(92, 87, 'God bless you for this', CURRENT_TIMESTAMP - interval '37 hours'),
(53, 7, 'Facts 💯', CURRENT_TIMESTAMP - interval '22 hours'),
(80, 73, 'I gave up on this course long ago', CURRENT_TIMESTAMP - interval '44 hours'),
(140, 58, 'Check your DMs', CURRENT_TIMESTAMP - interval '5 hours'),
(88, 8, 'I need a study group for this', CURRENT_TIMESTAMP - interval '29 hours'),
(2, 65, 'This is so true', CURRENT_TIMESTAMP - interval '10 hours'),
(109, 5, 'I need a study group for this', CURRENT_TIMESTAMP - interval '3 hours'),
(5, 58, 'This is so true', CURRENT_TIMESTAMP - interval '20 hours'),
(137, 7, 'I felt this in my soul', CURRENT_TIMESTAMP - interval '10 hours'),
(140, 57, 'Conti boys are quiet today 🤣', CURRENT_TIMESTAMP - interval '19 hours'),
(28, 12, 'This is so true', CURRENT_TIMESTAMP - interval '39 hours'),
(60, 21, 'This is so true', CURRENT_TIMESTAMP - interval '8 hours'),
(89, 35, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '22 hours'),
(107, 46, 'Eduroam is a scam', CURRENT_TIMESTAMP - interval '38 hours'),
(84, 19, 'Does anyone have the link?', CURRENT_TIMESTAMP - interval '10 hours'),
(95, 2, 'I thought I was the only one!', CURRENT_TIMESTAMP - interval '36 hours'),
(48, 66, 'Fr 😭', CURRENT_TIMESTAMP - interval '26 hours'),
(63, 98, 'Thanks for sharing!', CURRENT_TIMESTAMP - interval '30 hours'),
(116, 18, 'Help me please 😭', CURRENT_TIMESTAMP - interval '23 hours'),
(126, 21, 'Is this going to be in the midsem?', CURRENT_TIMESTAMP - interval '38 hours');
